{
 "title": "Likes",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "txtboxCashtag", "label": "Cashtag", "query": "$btc" },
   { "name": "txtboxUser", "label": "User", "query": "CycloneReversal" },
   { "name": "switchLikesMentions", "label": "Likes/ Mentions", "query": "likes, mentions" },
   {
    "name": "switchMentionInterval",
    "label": "Mention time count interval",
    "query": "1m,5m,10m,20m,25m,30m,45m,1h,6h,12h,1d,7d"
   },
   { "name": "switchLikesRetweets", "label": "Likes/ Retweets", "query": "favorite_count,retweet_count" }
  ]
 },
 "panels": [
  {
   "title": "Fluctuations for user",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "//table_data =\r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${switchLikesRetweets}\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${txtboxUser}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"status_id\", \"cashtag\"])\r\n  |> map(fn:(r) => ({ r with insert_time: int(v: r.insert_time) }))\r\n  |> max(column: \"insert_time\")\r\n  |> group(columns: [\"status_id\"])\r\n  //|> pivot(\r\n  //  rowKey:[\"_time\"],\r\n  //  columnKey: [\"cashtag\"],\r\n  //  valueColumn: \"_value\"\r\n  //)\r\n  //|> columns(column: \"labels\")\r\n\r\n//if \"${switchLikesMentions}\" == \"likes\" then group(columns: [\"cashtag\"], tables: table_data)\r\n  //|> keep(columns: [\"_time\", \"_value\"])\r\n//else group(tables: table_data)\r\n  //|> window(every: ${switchMentionInterval})  \r\n  //|> count()\r\n  //|> group(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Per cashtag for user",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "table_data = \r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${switchLikesRetweets}\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${txtboxUser}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"status_id\", \"cashtag\"])\r\n  |> map(fn:(r) => ({ r with insert_time: int(v: r.insert_time) }))\r\n  |> max(column: \"insert_time\")\r\n  |> group(columns: [\"cashtag\"])\r\n\r\nif \"${switchLikesMentions}\" == \"likes\" then sum(tables: table_data)\r\n  |> group()\r\nelse count(tables: table_data)\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Fluctuations for cashtag",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "table_data =\r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${switchLikesRetweets}\")\r\n  |> filter(fn: (r) => r[\"cashtag\"] == \"${txtboxCashtag}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"status_id\", \"cashtag\"])\r\n  |> map(fn:(r) => ({ r with insert_time: int(v: r.insert_time) }))\r\n  |> max(column: \"insert_time\")\r\n  \r\nif \"${switchLikesMentions}\" == \"likes\" then group(columns: [\"cashtag\"], tables: table_data)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\nelse group(tables: table_data)\r\n  |> window(every: ${switchMentionInterval})  \r\n  |> count()\r\n  |> group(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "Per cashtag distinct",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "table_data = \r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${switchLikesRetweets}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"status_id\", \"cashtag\"])\r\n  |> map(fn:(r) => ({ r with insert_time: int(v: r.insert_time) }))\r\n  |> max(column: \"insert_time\")\r\n  |> group(columns: [\"cashtag\", \"user\"])\r\n  |> max()\r\n  |> group(columns: [\"cashtag\"])\r\n\r\nif \"${switchLikesMentions}\" == \"likes\" then sum(tables: table_data)\r\n  |> group()\r\nelse count(tables: table_data)\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Per cashtag",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "table_data = \r\nfrom(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"${switchLikesRetweets}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"status_id\", \"cashtag\"])\r\n  |> map(fn:(r) => ({ r with insert_time: int(v: r.insert_time) }))\r\n  |> max(column: \"insert_time\")\r\n  |> group(columns: [\"cashtag\"])\r\n\r\nif \"${switchLikesMentions}\" == \"likes\" then sum(tables: table_data)\r\n  |> group()\r\nelse count(tables: table_data)\r\n  |> group()"
    }
   ]
  }
 ]
}