{
 "title": "Likes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "txtboxCashtag", "label": "Cashtag", "query": "$btc" },
   { "name": "txtboxUser", "label": "User", "query": "lnetuser" }
  ]
 },
 "panels": [
  {
   "title": "Like fluctuations for user",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${txtboxUser}\")  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"user\", \"_start\", \"_stop\", \"_field\", \"_measurement\"])\r\n\r\n"
    }
   ]
  },
  {
   "title": "Like fluctuations for cashtag",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> filter(fn: (r) => r[\"cashtag\"] == \"${txtboxCashtag}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns:[\"_time\"])\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Likes per cashtag",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"user\", \"_start\", \"_stop\", \"_field\", \"_measurement\"])\r\n  |> sum()\r\n  |> map(fn: (r) => ({ _time: r._time, \"1\": r[\"cashtag\"], \"2\": r[\"_value\"]}))\r\n  |> rename(columns: { \"1\": \"cashtag\", \"2\": \"favourites\" })"
    }
   ]
  }
 ]
}