{
 "title": "Mentions",
 "time": { "from": "2022-02-05T12:46:53.295Z", "to": "2022-02-06T00:46:53.295Z" },
 "templating": {
  "list": [
   { "name": "txtboxCashtag", "label": "Cashtag", "query": "$btc" },
   { "name": "txtboxUser", "label": "User", "query": "lnetuser" },
   { "name": "txtboxTimewindow", "label": "Time window", "query": "60" }
  ]
 },
 "panels": [
  {
   "title": "Mention fluctuations for user",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${txtboxUser}\")  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"user\", \"_start\", \"_stop\", \"_field\", \"_measurement\"])\r\n  |> truncateTimeColumn(unit: ${txtboxTimewindow}m)  \r\n  |> group()\r\n  |> map(fn: (r) => ({ _time: r._time, cashtag: r.cashtag, _value: 1 }))\r\n  |> group(columns: [\"cashtag\"])  \r\n\r\n  \r\n\r\n"
    }
   ]
  },
  {
   "title": "Mention fluctuations for cashtag",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> filter(fn: (r) => r[\"cashtag\"] == \"${txtboxCashtag}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_measurement\"])  \r\n  |> truncateTimeColumn(unit: ${txtboxTimewindow}m)\r\n  |> group(columns: [\"_time\"])\r\n  |> count()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Mentions per cashtag",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cashtag_grab\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Favorite_count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"user\", \"_start\", \"_stop\", \"_field\", \"_measurement\"])  \r\n  |> count()\r\n  |> group()\r\n"
    }
   ]
  }
 ]
}